### ISSUE TITLE
DCM4CHE and Medkey citations in Medicator

### ISSUE THREAD

**Issue by KonradHoeffner** [hitontology/database#23]
Medicator has citations Dcm4CheFeatModalityPerformedProcedureStep, Dcm4CheFeatModalityWorklist and MedkeyFeatDashboardVisualAnalytics, this can't be correct.
 
Please investigate, whether:

1. Those citation URIs are wrongly named, in this case rename them (the ID only! and please care about the naming conventions, see https://github.com/hitontology/ontology/issues/57)
2. Those citations URIs don't belong here, in this case change the software product to DCM4CHE, respectively Medkey.

See https://hitontology.eu/database-frontend/softwareproductview/show/Medicator

**Comment by MichelleBindel** [comment]
I checked them and changed the respective software products, the IDs were correct. Medicator is the default option for the software product, i guess thats why they slipped into Medicator. Thanks for catching that @KonradHoeffner!

**Comment by KonradHoeffner** [comment]
Thanks for fixing it @MichelleBindel!

This kind of error could be detected automatically, I am thinking about creating a dashboard and quality check tool like we have for the SNIK project at:

![snik-qualitycheck](https://user-images.githubusercontent.com/839577/115533154-c0e59e80-a296-11eb-86f2-c59c34795035.png)
![snik-dashboard](https://user-images.githubusercontent.com/839577/115533166-c4792580-a296-11eb-93a8-48193e82d0f8.png)

- https://imise.github.io/snik-ontology/2017/06/01/qualitycheck/
- https://imise.github.io/snik-ontology/2017/04/12/dashboard/

The links above may not initially load correctly due to CORS errors, in Firefox they work after installing the CorsE extension and enabling it:
- https://addons.mozilla.org/en-US/firefox/addon/cors-everywhere/

Care to not have that active all the time as it weakens browser security.

What do you think, do you have some metrics and possible errors in mind?

The tool would work on the SPARQL endpoint level, so it would lag behind the database and still show errors that have been fixed there but not yet been merged into the endpoint, but other than that I could imagine that being useful.
