### ISSUE TITLE
Load external data

### ISSUE THREAD

**Issue by KonradHoeffner** [hitontology/database#4]
- [x] load language from DBpedia
- [x] load license from SWO
- [x] programming languages from DBpedia

| property            | domain                           | comment             |
|---------------------|----------------------------------|---------------------|
| language            | dbo:Language                     | dbo:iso6391Code []. |
| license             | swo:SWO_0000002                  | transitive subclass |
| programmingLanguage | yago:WikicatProgrammingLanguages |                     |
|operatingSystem||
See github.com/hitontology/instancegenerator/ for custom queries.

**Comment by KonradHoeffner** [comment]
```
SELECT *
{
 ?p a owl:ObjectProperty;
  rdfs:domain hito:SoftwareProduct;
  rdfs:range ?range.
  FILTER(!STRSTARTS(str(?range),"http://hitontology.eu"))
  FILTER(?range!=rdfs:Resource)
}
```


p | range
-- | --
http://hitontology.eu/ontology/license | http://www.ebi.ac.uk/swo/SWO_0000002
http://hitontology.eu/ontology/programmingLanguage | http://dbpedia.org/class/yago/WikicatProgrammingLanguages
http://hitontology.eu/ontology/language | http://dbpedia.org/ontology/Language

**Comment by ThomasPause** [comment]
done.
